              //**  Jay KalBhirva    **//
import NextAuthProvider from "@/NextAuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/Components/Header";
import Footer from "@/Components/Sections/Footer";
import { Provider } from "react-redux";
import { store } from "@/store";
import ReduxProvider from "@/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextAuthProvider>
        <ReduxProvider>
        
      
            <Header />
            {children}
            <Footer />
            
          </ReduxProvider>
        
        </NextAuthProvider>
      </body>
    </html>
  );
}
